# Site settings
author: Levi Leal
title: CodeZ1
description: "CodeZone"
email: leviplj@gmail.com
baseurl: "/codez1"
url: "crimolt.github.io"


# Social
github: https://github.com/leviplj
twiter: jLeviLeal
facebook: jLeviLeal


#Build settings
destination: _site
markdown: kramdown
permalink: /blog/:title
sass:
  style: compressed
excerpt_separator: <!--more-->
exclude: ['node_modules', 'gulpfile.js', 'README.md', 'package.json', '*.sh', 'Gemfile', ]