# Site settings
title: CodeZ1
email: leviplj@gmail.com
description: "CodeZone"
baseurl: "/codez1"
url: "crimolt.github.io"


#Build settings
destination: .dist
markdown: kramdown
permalink: /blog/:title
sass:
  style: compressed
excerpt_separator: <!--more-->
exclude: ['node_modules', 'gulpfile.js', 'README.md', 'package.json']